# Generated by Django 4.2.5 on 2024-10-18 12:54

import company.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lookup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo_img', models.ImageField(blank=True, null=True, upload_to=company.models.upload_logo_to)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=200, null=True)),
                ('brand_color', models.CharField(blank=True, max_length=200, null=True)),
                ('tin', models.CharField(blank=True, max_length=200, null=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lookup.currency')),
            ],
        ),
    ]
