# Generated by Django 4.2.5 on 2024-11-14 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0002_alter_activitylog_action'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-timestamp']},
        ),
    ]
