# Generated by Django 4.2.5 on 2024-08-29 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_role_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_online',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2024, 8, 29, 13, 56, 56, 20187, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
