# Generated by Django 4.2.5 on 2024-08-28 15:11

from django.db import migrations, models
import django.db.models.deletion
import leave.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0008_alter_employee_bank_acc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('reason', models.CharField(blank=True, max_length=250, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to=leave.models.upload_to)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
    ]
