# Generated by Django 4.2.5 on 2024-09-03 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_alter_employee_email_alter_employee_gender_and_more'),
        ('lookup', '0007_currency'),
        ('leave', '0003_leave_leave_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='allow_atteched_docs',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='allow_negative',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='approval',
            field=models.CharField(choices=[('NO_VALIDATION', 'No Validation'), ('ADMIN', 'Admin')], default='NO_VALIDATION', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leavetype',
            name='can_carryover',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='carryover_period',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='eligible_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lookup.department'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='eligible_gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='eligible_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lookup.jobposition'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='eligible_worked_period',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='holiday_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='kind',
            field=models.CharField(choices=[('ABSENCE', 'Absence'), ('WORKED_TIME', 'Worked Time')], default='ABSENCE', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leavetype',
            name='max_accrued_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='max_carryover_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='max_taken_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='negative_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='notified_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='take_in',
            field=models.CharField(choices=[('DAY', 'Day'), ('HALF_DAY', 'Half-day'), ('HOUR', 'Hour')], default='DAY', max_length=50),
            preserve_default=False,
        ),
    ]
