# Generated by Django 4.2.5 on 2024-09-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_alter_employee_email_alter_employee_gender_and_more'),
        ('leave', '0004_leavetype_allow_atteched_docs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavetype',
            name='notified_officer',
        ),
        migrations.AddField(
            model_name='leavetype',
            name='notified_officer',
            field=models.ManyToManyField(blank=True, null=True, to='employee.employee'),
        ),
    ]
