# Generated by Django 4.2.5 on 2024-09-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_employee_active_employee_annual_leave_balance_and_more'),
        ('leave', '0005_remove_leavetype_notified_officer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetype',
            name='notified_officer',
            field=models.ManyToManyField(to='employee.employee'),
        ),
    ]
