# Generated by Django 4.2.5 on 2024-11-02 14:17

from django.db import migrations, models
import django.db.models.deletion
import leave.models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0006_leavebalance_last_increment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='document',
        ),
        migrations.CreateModel(
            name='LeaveRequestAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=leave.models.upload_to)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='leave.leave')),
            ],
        ),
    ]
