# Generated by Django 4.2.5 on 2024-10-31 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_remove_employee_income_tax_and_more'),
        ('attendance', '0002_attendance_break_end_attendance_break_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(blank=True, choices=[('ON_TIME', 'On Time'), ('LATE', 'Late')], max_length=200, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employee', 'date')},
        ),
    ]
