# Generated by Django 4.2.5 on 2024-10-20 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0003_remove_employee_income_tax_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payPeriod', models.DateField()),
                ('processed_date', models.DateField(auto_now_add=True)),
                ('basic_salary', models.FloatField()),
                ('non_tax_transp_allow', models.FloatField(default=0)),
                ('transp_allow', models.FloatField(default=0)),
                ('tele_allow', models.FloatField(default=0)),
                ('pos_allow', models.FloatField(default=0)),
                ('overtime', models.FloatField(default=0)),
                ('penalty', models.FloatField(default=0)),
                ('gross_earning', models.FloatField(default=0)),
                ('taxable_income', models.FloatField(default=0)),
                ('income_tax', models.FloatField(default=0)),
                ('staff_loan', models.FloatField(default=0)),
                ('cost_sharing', models.FloatField(default=0)),
                ('pension_7', models.FloatField(default=0)),
                ('pension_11', models.FloatField(default=0)),
                ('other_deductions', models.FloatField(default=0)),
                ('total_deduction', models.FloatField(default=0)),
                ('net_salary', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending')], default='pending', max_length=200)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'unique_together': {('employee', 'payPeriod')},
            },
        ),
    ]
