# Generated by Django 4.2.5 on 2024-08-14 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0003_rename_jop_position_employee_job_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('basic_salary', models.IntegerField()),
                ('non_tax_transp_allow', models.IntegerField(blank=True, null=True)),
                ('transp_allow', models.IntegerField(blank=True, null=True)),
                ('tele_allow', models.IntegerField(blank=True, null=True)),
                ('pos_allow', models.IntegerField(blank=True, null=True)),
                ('overtime', models.IntegerField(blank=True, null=True)),
                ('penalty', models.IntegerField(blank=True, null=True)),
                ('gross_earning', models.IntegerField(blank=True, null=True)),
                ('taxable_income', models.IntegerField(blank=True, null=True)),
                ('income_tax', models.IntegerField(blank=True, null=True)),
                ('staff_loan', models.IntegerField(blank=True, null=True)),
                ('cost_sharing', models.IntegerField(blank=True, null=True)),
                ('pension_7', models.IntegerField(blank=True, null=True)),
                ('pension_11', models.IntegerField(blank=True, null=True)),
                ('other_deductions', models.IntegerField(blank=True, null=True)),
                ('total_deduction', models.IntegerField(blank=True, null=True)),
                ('net_salary', models.IntegerField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslip_employee', to='employee.employee')),
            ],
        ),
    ]
