# Generated by Django 4.2.5 on 2024-10-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_alter_payroll_payperiod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='payPeriod',
            field=models.CharField(max_length=100),
        ),
    ]
