# Generated by Django 4.2.5 on 2024-08-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_alter_payslip_cost_sharing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='basic_salary',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='cost_sharing',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='gross_earning',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='income_tax',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='net_salary',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='non_tax_transp_allow',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='other_deductions',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='overtime',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='penalty',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='pension_11',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='pension_7',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='pos_allow',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='staff_loan',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='taxable_income',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='tele_allow',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='total_deduction',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='transp_allow',
            field=models.FloatField(default=0),
        ),
    ]
