# Generated by Django 4.2.5 on 2024-10-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_alter_payroll_payperiod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='payPeriod',
            field=models.CharField(max_length=20),
        ),
    ]
