# Generated by Django 4.2.5 on 2024-10-23 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0001_initial'),
        ('payroll', '0005_alter_payroll_payperiod'),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regular_working_hours', models.DecimalField(decimal_places=2, default=8.0, max_digits=4)),
                ('overtime_multiplier', models.DecimalField(decimal_places=2, default=1.5, max_digits=3)),
                ('max_regular_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lookup.department')),
            ],
        ),
    ]
