# Generated by Django 4.2.5 on 2024-08-16 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_payroll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='date_generated',
            field=models.DateField(default=datetime.datetime(2024, 8, 16, 16, 11, 13, 280838)),
        ),
    ]
