# Generated by Django 4.2.5 on 2024-08-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_alter_payroll_date_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='date_generated',
            field=models.DateField(auto_now=True),
        ),
    ]
