# Generated by Django 4.2.5 on 2024-07-23 08:07

from django.db import migrations, models
import django.db.models.deletion
import employee.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lookup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('bdate', models.DateField()),
                ('profilePic', models.ImageField(blank=True, null=True, upload_to=employee.models.upload_profile_to)),
                ('idImg', models.ImageField(blank=True, null=True, upload_to=employee.models.upload_id_to)),
                ('bank_acc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lookup.bankaccount')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lookup.department')),
                ('jop_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lookup.jobposition')),
            ],
        ),
    ]
