# Generated by Django 4.2.5 on 2024-10-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='basic_salary',
            field=models.FloatField(default=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='cost_sharing',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='income_tax',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='non_tax_transp_allow',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='other_deductions',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='pension_11',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='pension_7',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='pos_allow',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='staff_loan',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='tele_allow',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='transp_allow',
            field=models.FloatField(default=0),
        ),
    ]
