# Generated by Django 4.2.5 on 2024-10-18 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_basic_salary_employee_cost_sharing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='income_tax',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='pension_11',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='pension_7',
        ),
    ]
