# Generated by Django 4.2.5 on 2024-08-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_employee_bank_acc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='bank_acc',
            field=models.CharField(blank=True, null=True),
        ),
    ]
