# Generated by Django 4.2.5 on 2024-08-31 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_alter_employee_bank_acc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='bdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
