# Generated by Django 4.2.5 on 2024-08-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0003_degree_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='bank',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
