# Generated by Django 4.2.5 on 2024-08-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0004_alter_bankaccount_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='accountNo',
            field=models.CharField(max_length=200),
        ),
    ]
