# Generated by Django 4.2.5 on 2024-08-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_recruitment_job_position_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment',
            name='target',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
