# Generated by Django 4.2.5 on 2024-08-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_alter_recruitment_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment',
            name='job_position_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
