# Generated by Django 4.2.5 on 2024-08-09 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_application_job_position_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='job_position_id',
        ),
    ]
