# Generated by Django 4.2.5 on 2024-08-09 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0006_remove_application_job_position_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='applicant_id',
            new_name='applicant',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='recruitment_id',
            new_name='recruitment',
        ),
    ]
