# Generated by Django 4.2.5 on 2024-08-13 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0003_degree_stage'),
        ('employee', '0002_alter_employee_bank_acc_alter_employee_department_and_more'),
        ('recruitment', '0008_alter_applicant_degree_alter_application_applicant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appl_degree', to='lookup.degree'),
        ),
        migrations.AlterField(
            model_name='application',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_applicant', to='recruitment.applicant'),
        ),
        migrations.AlterField(
            model_name='application',
            name='department_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_department', to='lookup.department'),
        ),
        migrations.AlterField(
            model_name='application',
            name='recruitment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_recruitment', to='recruitment.recruitment'),
        ),
        migrations.AlterField(
            model_name='application',
            name='stage_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_stage', to='lookup.stage'),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='recruiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruiter', to='employee.employee'),
        ),
    ]
