# Generated by Django 4.2.5 on 2024-08-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0009_alter_applicant_degree_alter_application_applicant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='linkidin_profile',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
