# Generated by Django 4.2.5 on 2024-08-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0010_alter_applicant_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='expected_salary',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='proposed_salary',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
