# Generated by Django 4.2.5 on 2024-08-31 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_brand_color_company_currency_company_tin_and_more'),
        ('recruitment', '0011_alter_application_expected_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
    ]
